import 'footprint_models.dart';

const FootprintPoint _originCenter = FootprintPoint(0, 0);

const FootprintStyleTokens _defaultStyleTokens = FootprintStyleTokens(
  strokeToken: 'footprint.stroke.default',
  fillToken: 'footprint.fill.default',
  opacityToken: 'footprint.opacity.default',
  lineStyleToken: 'footprint.line.default',
  label: 'package geometry visual metadata only',
);

const FootprintLodHints _defaultLodHints = FootprintLodHints(
  minVisibleZoom: 0.0,
  fullDetailZoom: 1.5,
  collapsePinsBelowZoom: 0.6,
  note: 'renderer metadata only',
);

const FootprintLabelAnchor _centerLabelAnchor = FootprintLabelAnchor(
  point: FootprintPoint(0, 0),
  alignment: 'center',
);

const FootprintOrientationMarker _topLeftMarker = FootprintOrientationMarker(
  point: FootprintPoint(-0.35, -0.2),
  markerType: 'dot',
  size: 0.05,
);

const FootprintHitTestShape _defaultHitTestShape = FootprintHitTestShape(
  kind: FootprintHitTestKind.boundingBox,
  bounds: FootprintBoundingBox(
    minX: -0.7,
    minY: -0.4,
    maxX: 0.7,
    maxY: 0.4,
  ),
  note: 'interaction metadata only',
);

const List<FootprintTemplate> kV1FootprintTemplates = [
  FootprintTemplate(
    templateId: 'unknown_rect',
    templateVersion: 'v1',
    packageFamily: 'unknown_generic',
    displayName: 'Unknown rectangular package',
    description: 'Geometry fallback only for unknown rectangular outline.',
    body: FootprintBody(
      shape: FootprintBodyShape.rect,
      width: 1.0,
      height: 0.6,
    ),
    origin: _originCenter,
    boundingBox: FootprintBoundingBox(minX: -0.5, minY: -0.3, maxX: 0.5, maxY: 0.3),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(minPins: 0, maxPins: 0),
    defaultPinPitch: 0.4,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: FootprintHitTestShape(
      kind: FootprintHitTestKind.boundingBox,
      bounds:
          FootprintBoundingBox(minX: -0.5, minY: -0.3, maxX: 0.5, maxY: 0.3),
      note: 'interaction metadata only',
    ),
    accessibilityLabelTemplate: 'Unknown geometry fallback rectangle',
    fallbackPolicy: FootprintFallbackPolicy.geometryOnlyFallback,
  ),
  FootprintTemplate(
    templateId: 'unknown_2pin',
    templateVersion: 'v1',
    packageFamily: 'unknown_generic',
    displayName: 'Unknown two-pin package',
    description: 'Geometry fallback only for unknown two-pin package.',
    body: FootprintBody(
      shape: FootprintBodyShape.rect,
      width: 1.0,
      height: 0.5,
    ),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.75, minY: -0.25, maxX: 0.75, maxY: 0.25),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.7, 0),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.18,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(0.7, 0),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.18,
      ),
    ],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(fixedCount: 2),
    defaultPinPitch: 1.4,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Unknown geometry fallback two-pin package',
    fallbackPolicy: FootprintFallbackPolicy.geometryOnlyFallback,
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'unknown_3pin',
    templateVersion: 'v1',
    packageFamily: 'unknown_generic',
    displayName: 'Unknown three-pin package',
    description: 'Geometry fallback only for unknown three-pin package.',
    body: FootprintBody(
      shape: FootprintBodyShape.rect,
      width: 1.0,
      height: 0.6,
    ),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.75, minY: -0.3, maxX: 0.75, maxY: 0.3),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.7, -0.2),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.14,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(-0.7, 0.2),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.14,
      ),
      FootprintPinAnchor(
        pinNumber: 3,
        anchor: FootprintPoint(0.7, 0),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.16,
      ),
    ],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(fixedCount: 3),
    defaultPinPitch: 0.4,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Unknown geometry fallback three-pin package',
    fallbackPolicy: FootprintFallbackPolicy.geometryOnlyFallback,
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'unknown_multi_pin',
    templateVersion: 'v1',
    packageFamily: 'unknown_generic',
    displayName: 'Unknown multi-pin package',
    description: 'Geometry fallback only for unknown multi-pin package.',
    body: FootprintBody(
      shape: FootprintBodyShape.rect,
      width: 1.2,
      height: 0.8,
    ),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.8, minY: -0.5, maxX: 0.8, maxY: 0.5),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.8, -0.2),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.14,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(-0.8, 0.2),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.14,
      ),
      FootprintPinAnchor(
        pinNumber: 3,
        anchor: FootprintPoint(0.8, -0.2),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.14,
      ),
      FootprintPinAnchor(
        pinNumber: 4,
        anchor: FootprintPoint(0.8, 0.2),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.14,
      ),
    ],
    pinGroups: [
      FootprintPinGroup(groupId: 'left_side', pinNumbers: [1, 2]),
      FootprintPinGroup(groupId: 'right_side', pinNumbers: [3, 4]),
    ],
    pinCountRules: FootprintPinCountRules(minPins: 4, maxPins: 64, variantDriven: true),
    defaultPinPitch: 0.4,
    allowedVariants: [
      FootprintVariant(
        variantId: 'default_4pin',
        pinsPerSide: {
          FootprintPinSide.left: 2,
          FootprintPinSide.right: 2,
        },
      ),
    ],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Unknown geometry fallback multi-pin package',
    fallbackPolicy: FootprintFallbackPolicy.geometryOnlyFallback,
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'chip_0402',
    templateVersion: 'v1',
    packageFamily: 'chip_passive',
    displayName: 'Chip package 0402',
    description: 'Small two-terminal chip package geometry.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 0.55, height: 0.3),
    origin: _originCenter,
    boundingBox: FootprintBoundingBox(minX: -0.45, minY: -0.2, maxX: 0.45, maxY: 0.2),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.4, 0),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.08,
        height: 0.12,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(0.4, 0),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.08,
        height: 0.12,
      ),
    ],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(fixedCount: 2),
    defaultPinPitch: 0.8,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Chip package 0402 geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'chip_0603',
    templateVersion: 'v1',
    packageFamily: 'chip_passive',
    displayName: 'Chip package 0603',
    description: 'Two-terminal chip package geometry.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 0.8, height: 0.45),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.55, minY: -0.25, maxX: 0.55, maxY: 0.25),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.5, 0),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.15,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(0.5, 0),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.15,
      ),
    ],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(fixedCount: 2),
    defaultPinPitch: 1.0,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Chip package 0603 geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'chip_0805',
    templateVersion: 'v1',
    packageFamily: 'chip_passive',
    displayName: 'Chip package 0805',
    description: 'Medium two-terminal chip package geometry.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 1.0, height: 0.55),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.65, minY: -0.3, maxX: 0.65, maxY: 0.3),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.6, 0),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.12,
        height: 0.18,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(0.6, 0),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.12,
        height: 0.18,
      ),
    ],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(fixedCount: 2),
    defaultPinPitch: 1.2,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Chip package 0805 geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'chip_1206',
    templateVersion: 'v1',
    packageFamily: 'chip_passive',
    displayName: 'Chip package 1206',
    description: 'Large two-terminal chip package geometry.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 1.35, height: 0.75),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.85, minY: -0.4, maxX: 0.85, maxY: 0.4),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.8, 0),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.14,
        height: 0.2,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(0.8, 0),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.14,
        height: 0.2,
      ),
    ],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(fixedCount: 2),
    defaultPinPitch: 1.6,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Chip package 1206 geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'two_pin_smd',
    templateVersion: 'v1',
    packageFamily: 'generic_smd',
    displayName: 'Two-pin SMD package',
    description: 'Generic two-pin surface-mount package geometry.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 1.0, height: 0.5),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.75, minY: -0.25, maxX: 0.75, maxY: 0.25),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.7, 0),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.16,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(0.7, 0),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.16,
      ),
    ],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(fixedCount: 2),
    defaultPinPitch: 1.4,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Generic two-pin SMD package geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'two_pin_axial',
    templateVersion: 'v1',
    packageFamily: 'axial_through_hole',
    displayName: 'Two-pin axial package',
    description: 'Generic two-pin axial package geometry.',
    body: FootprintBody(shape: FootprintBodyShape.oval, width: 1.0, height: 0.4),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.9, minY: -0.25, maxX: 0.9, maxY: 0.25),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.85, 0),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.circle,
        radius: 0.05,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(0.85, 0),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.circle,
        radius: 0.05,
      ),
    ],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(fixedCount: 2),
    defaultPinPitch: 1.7,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Generic two-pin axial package geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'three_pin_smd_generic',
    templateVersion: 'v1',
    packageFamily: 'generic_smd',
    displayName: 'Three-pin SMD package',
    description: 'Generic three-pin surface-mount package geometry.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 1.0, height: 0.8),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.8, minY: -0.4, maxX: 0.8, maxY: 0.4),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.75, -0.2),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.14,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(-0.75, 0.2),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.14,
      ),
      FootprintPinAnchor(
        pinNumber: 3,
        anchor: FootprintPoint(0.75, 0),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.14,
      ),
    ],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(fixedCount: 3),
    defaultPinPitch: 0.4,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Generic three-pin SMD package geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'three_pin_through_hole_generic',
    templateVersion: 'v1',
    packageFamily: 'generic_through_hole',
    displayName: 'Three-pin through-hole package',
    description: 'Generic three-pin through-hole package geometry.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 1.0, height: 0.6),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.75, minY: -0.35, maxX: 0.75, maxY: 0.35),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.5, 0.3),
        side: FootprintPinSide.bottom,
        shape: FootprintPinShape.circle,
        radius: 0.05,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(0, 0.3),
        side: FootprintPinSide.bottom,
        shape: FootprintPinShape.circle,
        radius: 0.05,
      ),
      FootprintPinAnchor(
        pinNumber: 3,
        anchor: FootprintPoint(0.5, 0.3),
        side: FootprintPinSide.bottom,
        shape: FootprintPinShape.circle,
        radius: 0.05,
      ),
    ],
    pinGroups: [FootprintPinGroup(groupId: 'bottom_row', pinNumbers: [1, 2, 3])],
    pinCountRules: FootprintPinCountRules(fixedCount: 3),
    defaultPinPitch: 0.5,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Generic three-pin through-hole package geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'sot23_3',
    templateVersion: 'v1',
    packageFamily: 'sot',
    displayName: 'SOT-23 (3-pin package)',
    description: 'SOT-23 style three-pin package geometry.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 0.9, height: 0.7),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.72, minY: -0.35, maxX: 0.72, maxY: 0.35),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: FootprintOrientationMarker(
      point: FootprintPoint(-0.2, -0.2),
      markerType: 'pin1_dot',
      size: 0.04,
    ),
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.7, -0.2),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.08,
        height: 0.12,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(-0.7, 0.2),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.08,
        height: 0.12,
      ),
      FootprintPinAnchor(
        pinNumber: 3,
        anchor: FootprintPoint(0.7, 0),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.08,
        height: 0.12,
      ),
    ],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(fixedCount: 3),
    defaultPinPitch: 0.4,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'SOT-23 three-pin package geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'sot23_5',
    templateVersion: 'v1',
    packageFamily: 'sot',
    displayName: 'SOT-23 (5-pin package)',
    description: 'SOT-23 style five-pin package geometry.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 1.0, height: 0.75),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.75, minY: -0.4, maxX: 0.75, maxY: 0.4),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: FootprintOrientationMarker(
      point: FootprintPoint(-0.2, -0.25),
      markerType: 'pin1_dot',
      size: 0.04,
    ),
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.72, -0.24),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.08,
        height: 0.1,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(-0.72, 0),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.08,
        height: 0.1,
      ),
      FootprintPinAnchor(
        pinNumber: 3,
        anchor: FootprintPoint(-0.72, 0.24),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.08,
        height: 0.1,
      ),
      FootprintPinAnchor(
        pinNumber: 4,
        anchor: FootprintPoint(0.72, -0.12),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.08,
        height: 0.1,
      ),
      FootprintPinAnchor(
        pinNumber: 5,
        anchor: FootprintPoint(0.72, 0.12),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.08,
        height: 0.1,
      ),
    ],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(fixedCount: 5),
    defaultPinPitch: 0.24,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'SOT-23 five-pin package geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'sot223',
    templateVersion: 'v1',
    packageFamily: 'sot',
    displayName: 'SOT-223 package',
    description: 'SOT-223 style package geometry with thermal tab.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 1.4, height: 1.2),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.95, minY: -0.7, maxX: 0.95, maxY: 0.7),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: FootprintOrientationMarker(
      point: FootprintPoint(-0.25, -0.35),
      markerType: 'pin1_dot',
      size: 0.05,
    ),
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.85, -0.35),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.12,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(-0.85, 0),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.12,
      ),
      FootprintPinAnchor(
        pinNumber: 3,
        anchor: FootprintPoint(-0.85, 0.35),
        side: FootprintPinSide.left,
        shape: FootprintPinShape.rect,
        width: 0.1,
        height: 0.12,
      ),
      FootprintPinAnchor(
        pinNumber: 4,
        anchor: FootprintPoint(0.88, 0),
        side: FootprintPinSide.right,
        shape: FootprintPinShape.rect,
        width: 0.16,
        height: 0.38,
      ),
    ],
    pinGroups: [],
    pinCountRules: FootprintPinCountRules(fixedCount: 4),
    defaultPinPitch: 0.35,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'SOT-223 package geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'soic_8',
    templateVersion: 'v1',
    packageFamily: 'soic',
    displayName: 'SOIC-8 package',
    description: 'SOIC-8 package geometry with gull-wing leads.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 1.2, height: 0.9),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.95, minY: -0.55, maxX: 0.95, maxY: 0.55),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: FootprintOrientationMarker(
      point: FootprintPoint(-0.3, -0.25),
      markerType: 'pin1_dot',
      size: 0.05,
    ),
    pinAnchors: [
      FootprintPinAnchor(pinNumber: 1, anchor: FootprintPoint(-0.9, -0.36), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.09, height: 0.1),
      FootprintPinAnchor(pinNumber: 2, anchor: FootprintPoint(-0.9, -0.12), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.09, height: 0.1),
      FootprintPinAnchor(pinNumber: 3, anchor: FootprintPoint(-0.9, 0.12), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.09, height: 0.1),
      FootprintPinAnchor(pinNumber: 4, anchor: FootprintPoint(-0.9, 0.36), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.09, height: 0.1),
      FootprintPinAnchor(pinNumber: 5, anchor: FootprintPoint(0.9, 0.36), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.09, height: 0.1),
      FootprintPinAnchor(pinNumber: 6, anchor: FootprintPoint(0.9, 0.12), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.09, height: 0.1),
      FootprintPinAnchor(pinNumber: 7, anchor: FootprintPoint(0.9, -0.12), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.09, height: 0.1),
      FootprintPinAnchor(pinNumber: 8, anchor: FootprintPoint(0.9, -0.36), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.09, height: 0.1),
    ],
    pinGroups: [
      FootprintPinGroup(groupId: 'left_side', pinNumbers: [1, 2, 3, 4]),
      FootprintPinGroup(groupId: 'right_side', pinNumbers: [5, 6, 7, 8]),
    ],
    pinCountRules: FootprintPinCountRules(fixedCount: 8),
    defaultPinPitch: 0.24,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'SOIC-8 package geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'soic_14',
    templateVersion: 'v1',
    packageFamily: 'soic',
    displayName: 'SOIC-14 package',
    description: 'SOIC-14 package geometry with gull-wing leads.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 1.6, height: 1.1),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -1.05, minY: -0.7, maxX: 1.05, maxY: 0.7),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: FootprintOrientationMarker(
      point: FootprintPoint(-0.4, -0.35),
      markerType: 'pin1_dot',
      size: 0.05,
    ),
    pinAnchors: [
      FootprintPinAnchor(pinNumber: 1, anchor: FootprintPoint(-1.0, -0.54), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 2, anchor: FootprintPoint(-1.0, -0.36), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 3, anchor: FootprintPoint(-1.0, -0.18), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 4, anchor: FootprintPoint(-1.0, 0.0), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 5, anchor: FootprintPoint(-1.0, 0.18), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 6, anchor: FootprintPoint(-1.0, 0.36), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 7, anchor: FootprintPoint(-1.0, 0.54), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 8, anchor: FootprintPoint(1.0, 0.54), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 9, anchor: FootprintPoint(1.0, 0.36), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 10, anchor: FootprintPoint(1.0, 0.18), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 11, anchor: FootprintPoint(1.0, 0.0), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 12, anchor: FootprintPoint(1.0, -0.18), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 13, anchor: FootprintPoint(1.0, -0.36), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 14, anchor: FootprintPoint(1.0, -0.54), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
    ],
    pinGroups: [
      FootprintPinGroup(groupId: 'left_side', pinNumbers: [1, 2, 3, 4, 5, 6, 7]),
      FootprintPinGroup(groupId: 'right_side', pinNumbers: [8, 9, 10, 11, 12, 13, 14]),
    ],
    pinCountRules: FootprintPinCountRules(fixedCount: 14),
    defaultPinPitch: 0.18,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'SOIC-14 package geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'soic_16',
    templateVersion: 'v1',
    packageFamily: 'soic',
    displayName: 'SOIC-16 package',
    description: 'SOIC-16 package geometry with gull-wing leads.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 1.8, height: 1.2),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -1.1, minY: -0.75, maxX: 1.1, maxY: 0.75),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: FootprintOrientationMarker(
      point: FootprintPoint(-0.45, -0.38),
      markerType: 'pin1_dot',
      size: 0.05,
    ),
    pinAnchors: [
      FootprintPinAnchor(pinNumber: 1, anchor: FootprintPoint(-1.05, -0.63), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 2, anchor: FootprintPoint(-1.05, -0.45), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 3, anchor: FootprintPoint(-1.05, -0.27), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 4, anchor: FootprintPoint(-1.05, -0.09), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 5, anchor: FootprintPoint(-1.05, 0.09), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 6, anchor: FootprintPoint(-1.05, 0.27), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 7, anchor: FootprintPoint(-1.05, 0.45), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 8, anchor: FootprintPoint(-1.05, 0.63), side: FootprintPinSide.left, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 9, anchor: FootprintPoint(1.05, 0.63), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 10, anchor: FootprintPoint(1.05, 0.45), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 11, anchor: FootprintPoint(1.05, 0.27), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 12, anchor: FootprintPoint(1.05, 0.09), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 13, anchor: FootprintPoint(1.05, -0.09), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 14, anchor: FootprintPoint(1.05, -0.27), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 15, anchor: FootprintPoint(1.05, -0.45), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
      FootprintPinAnchor(pinNumber: 16, anchor: FootprintPoint(1.05, -0.63), side: FootprintPinSide.right, shape: FootprintPinShape.rect, width: 0.08, height: 0.09),
    ],
    pinGroups: [
      FootprintPinGroup(groupId: 'left_side', pinNumbers: [1, 2, 3, 4, 5, 6, 7, 8]),
      FootprintPinGroup(groupId: 'right_side', pinNumbers: [9, 10, 11, 12, 13, 14, 15, 16]),
    ],
    pinCountRules: FootprintPinCountRules(fixedCount: 16),
    defaultPinPitch: 0.18,
    allowedVariants: [],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'SOIC-16 package geometry',
    allowsExternalLeadExtents: true,
  ),
  FootprintTemplate(
    templateId: 'header_1xn',
    templateVersion: 'v1',
    packageFamily: 'header',
    displayName: 'Header 1xN package',
    description: 'Single-row header package geometry.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 1.2, height: 0.4),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.7, minY: -0.25, maxX: 0.7, maxY: 0.25),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.4, 0),
        side: FootprintPinSide.bottom,
        shape: FootprintPinShape.circle,
        radius: 0.05,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(0.4, 0),
        side: FootprintPinSide.bottom,
        shape: FootprintPinShape.circle,
        radius: 0.05,
      ),
    ],
    pinGroups: [FootprintPinGroup(groupId: 'row_1', pinNumbers: [1, 2])],
    pinCountRules: FootprintPinCountRules(minPins: 2, maxPins: 40, variantDriven: true),
    defaultPinPitch: 0.2,
    allowedVariants: [
      FootprintVariant(
        variantId: 'header_1x2',
        pinsPerSide: {FootprintPinSide.bottom: 2},
        pitch: 0.2,
      ),
    ],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Header one-row package geometry',
  ),
  FootprintTemplate(
    templateId: 'header_2xn',
    templateVersion: 'v1',
    packageFamily: 'header',
    displayName: 'Header 2xN package',
    description: 'Two-row header package geometry.',
    body: FootprintBody(shape: FootprintBodyShape.rect, width: 1.2, height: 0.8),
    origin: _originCenter,
    boundingBox:
        FootprintBoundingBox(minX: -0.7, minY: -0.4, maxX: 0.7, maxY: 0.4),
    labelAnchor: _centerLabelAnchor,
    orientationMarker: _topLeftMarker,
    pinAnchors: [
      FootprintPinAnchor(
        pinNumber: 1,
        anchor: FootprintPoint(-0.4, -0.2),
        side: FootprintPinSide.bottom,
        shape: FootprintPinShape.circle,
        radius: 0.05,
      ),
      FootprintPinAnchor(
        pinNumber: 2,
        anchor: FootprintPoint(-0.4, 0.2),
        side: FootprintPinSide.top,
        shape: FootprintPinShape.circle,
        radius: 0.05,
      ),
      FootprintPinAnchor(
        pinNumber: 3,
        anchor: FootprintPoint(0.4, -0.2),
        side: FootprintPinSide.bottom,
        shape: FootprintPinShape.circle,
        radius: 0.05,
      ),
      FootprintPinAnchor(
        pinNumber: 4,
        anchor: FootprintPoint(0.4, 0.2),
        side: FootprintPinSide.top,
        shape: FootprintPinShape.circle,
        radius: 0.05,
      ),
    ],
    pinGroups: [
      FootprintPinGroup(groupId: 'row_a', pinNumbers: [1, 3]),
      FootprintPinGroup(groupId: 'row_b', pinNumbers: [2, 4]),
    ],
    pinCountRules: FootprintPinCountRules(minPins: 4, maxPins: 80, variantDriven: true),
    defaultPinPitch: 0.2,
    allowedVariants: [
      FootprintVariant(
        variantId: 'header_2x2',
        pinsPerSide: {
          FootprintPinSide.top: 2,
          FootprintPinSide.bottom: 2,
        },
        pitch: 0.2,
      ),
    ],
    defaultStyleTokens: _defaultStyleTokens,
    lodHints: _defaultLodHints,
    hitTestShape: _defaultHitTestShape,
    accessibilityLabelTemplate: 'Header two-row package geometry',
  ),
];

class VectorFootprintLibrary {
  const VectorFootprintLibrary._();

  static const List<FootprintTemplate> templates = kV1FootprintTemplates;

  static final Map<String, FootprintTemplate> templatesById = {
    for (final template in templates) template.templateId: template,
  };

  static FootprintTemplate? templateById(String templateId) {
    return templatesById[templateId];
  }
}
